// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

// protoc -I=$SRC_DIR --go_out=$DST_DIR $SRC_DIR/hello.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloMessageReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloMessageReq) Reset()         { *m = HelloMessageReq{} }
func (m *HelloMessageReq) String() string { return proto.CompactTextString(m) }
func (*HelloMessageReq) ProtoMessage()    {}
func (*HelloMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *HelloMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloMessageReq.Unmarshal(m, b)
}
func (m *HelloMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloMessageReq.Marshal(b, m, deterministic)
}
func (m *HelloMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloMessageReq.Merge(m, src)
}
func (m *HelloMessageReq) XXX_Size() int {
	return xxx_messageInfo_HelloMessageReq.Size(m)
}
func (m *HelloMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_HelloMessageReq proto.InternalMessageInfo

func (m *HelloMessageReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloMessageRsp struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloMessageRsp) Reset()         { *m = HelloMessageRsp{} }
func (m *HelloMessageRsp) String() string { return proto.CompactTextString(m) }
func (*HelloMessageRsp) ProtoMessage()    {}
func (*HelloMessageRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *HelloMessageRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloMessageRsp.Unmarshal(m, b)
}
func (m *HelloMessageRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloMessageRsp.Marshal(b, m, deterministic)
}
func (m *HelloMessageRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloMessageRsp.Merge(m, src)
}
func (m *HelloMessageRsp) XXX_Size() int {
	return xxx_messageInfo_HelloMessageRsp.Size(m)
}
func (m *HelloMessageRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloMessageRsp.DiscardUnknown(m)
}

var xxx_messageInfo_HelloMessageRsp proto.InternalMessageInfo

func (m *HelloMessageRsp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloMessageReq)(nil), "example.HelloMessageReq")
	proto.RegisterType((*HelloMessageRsp)(nil), "example.HelloMessageRsp")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49,
	0x55, 0x52, 0xe5, 0xe2, 0xf7, 0x00, 0x89, 0xfb, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x06, 0xa5,
	0x16, 0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x81, 0xd9, 0x4a, 0x9a, 0x68, 0xca, 0x8a, 0x0b, 0x84, 0xc4, 0xb8, 0xd8, 0x8a, 0x52, 0x8b, 0x4b,
	0x73, 0x4a, 0xa0, 0x0a, 0xa1, 0xbc, 0x24, 0x36, 0xb0, 0x0d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x0f, 0x65, 0xfc, 0x78, 0x70, 0x00, 0x00, 0x00,
}
