// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im.proto

// protoc -I=. --go_out=. im.proto

package im

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	FormId               int64    `protobuf:"varint,3,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	ToId                 int64    `protobuf:"varint,4,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Message) GetFormId() int64 {
	if m != nil {
		return m.FormId
	}
	return 0
}

func (m *Message) GetToId() int64 {
	if m != nil {
		return m.ToId
	}
	return 0
}

func (m *Message) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "im.Message")
}

func init() { proto.RegisterFile("im.proto", fileDescriptor_36f2114a3e4ddb9e) }

var fileDescriptor_36f2114a3e4ddb9e = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xce, 0x31, 0x0e, 0xc2, 0x30,
	0x0c, 0x85, 0x61, 0x25, 0x6d, 0x5a, 0xf0, 0xc0, 0x60, 0x90, 0xf0, 0x58, 0x31, 0x65, 0x62, 0xe1,
	0x14, 0x1d, 0x58, 0x72, 0x01, 0x04, 0x24, 0x20, 0x4b, 0xa4, 0xae, 0x5a, 0x2f, 0x9c, 0x81, 0x4b,
	0xa3, 0x06, 0xb1, 0xf9, 0xff, 0xe4, 0xe1, 0xc1, 0x8a, 0xf3, 0x71, 0x9c, 0x44, 0x05, 0x2d, 0xe7,
	0xc3, 0xc7, 0x40, 0x7b, 0x4e, 0xf3, 0x7c, 0x7d, 0x26, 0xdc, 0x80, 0xe5, 0x48, 0xa6, 0x33, 0xbe,
	0x0a, 0x96, 0x23, 0x22, 0xd4, 0xfa, 0x1e, 0x13, 0xd9, 0xce, 0x78, 0x17, 0xca, 0x8d, 0x7b, 0x68,
	0x1f, 0x32, 0xe5, 0x0b, 0x47, 0xaa, 0xca, 0x63, 0xb3, 0x64, 0x1f, 0x71, 0x0b, 0x4e, 0x65, 0xe1,
	0xba, 0x70, 0xad, 0xd2, 0x47, 0xdc, 0x81, 0x53, 0xd6, 0x57, 0x22, 0xd7, 0x19, 0xbf, 0x0e, 0xbf,
	0x40, 0x82, 0xf6, 0x2e, 0x83, 0xa6, 0x41, 0xa9, 0x29, 0xfe, 0xcf, 0x5b, 0x53, 0x86, 0x9d, 0xbe,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x49, 0xff, 0xba, 0xa4, 0x00, 0x00, 0x00,
}
