// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin.proto

// protoc -I=./ -I=../ --proto_path=C:/Users/Administrator/go/novel-go --go_out=. ./*.proto

package admin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	user "proto/user"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserListReq struct {
	User                 *user.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Page                 uint32     `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                uint32     `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserListReq) Reset()         { *m = UserListReq{} }
func (m *UserListReq) String() string { return proto.CompactTextString(m) }
func (*UserListReq) ProtoMessage()    {}
func (*UserListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{0}
}

func (m *UserListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListReq.Unmarshal(m, b)
}
func (m *UserListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListReq.Marshal(b, m, deterministic)
}
func (m *UserListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListReq.Merge(m, src)
}
func (m *UserListReq) XXX_Size() int {
	return xxx_messageInfo_UserListReq.Size(m)
}
func (m *UserListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserListReq proto.InternalMessageInfo

func (m *UserListReq) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserListReq) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UserListReq) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type UserListRsp struct {
	Code                 int32        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	List                 []*user.User `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Total                uint32       `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserListRsp) Reset()         { *m = UserListRsp{} }
func (m *UserListRsp) String() string { return proto.CompactTextString(m) }
func (*UserListRsp) ProtoMessage()    {}
func (*UserListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{1}
}

func (m *UserListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRsp.Unmarshal(m, b)
}
func (m *UserListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRsp.Marshal(b, m, deterministic)
}
func (m *UserListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRsp.Merge(m, src)
}
func (m *UserListRsp) XXX_Size() int {
	return xxx_messageInfo_UserListRsp.Size(m)
}
func (m *UserListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRsp proto.InternalMessageInfo

func (m *UserListRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserListRsp) GetList() []*user.User {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *UserListRsp) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*UserListReq)(nil), "admin.UserListReq")
	proto.RegisterType((*UserListRsp)(nil), "admin.UserListRsp")
}

func init() { proto.RegisterFile("admin.proto", fileDescriptor_73a7fc70dcc2027c) }

var fileDescriptor_73a7fc70dcc2027c = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4c, 0xc9, 0xcd,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0x44, 0xc1, 0x3c, 0xfd,
	0xd2, 0xe2, 0xd4, 0x22, 0x30, 0x01, 0x91, 0x55, 0x0a, 0xe7, 0xe2, 0x0e, 0x2d, 0x4e, 0x2d, 0xf2,
	0xc9, 0x2c, 0x2e, 0x09, 0x4a, 0x2d, 0x14, 0x92, 0xe3, 0x62, 0x01, 0x49, 0x4a, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x1b, 0x71, 0xe9, 0x81, 0x55, 0x82, 0x14, 0x04, 0x81, 0xc5, 0x85, 0x84, 0xb8, 0x58,
	0x0a, 0x12, 0xd3, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x78, 0x83, 0xc0, 0x6c, 0x21, 0x11, 0x2e,
	0xd6, 0x9c, 0xcc, 0xdc, 0xcc, 0x12, 0x09, 0x66, 0xb0, 0x20, 0x84, 0x83, 0x62, 0x70, 0x71, 0x01,
	0x48, 0x63, 0x72, 0x7e, 0x4a, 0x2a, 0xd8, 0x60, 0xd6, 0x20, 0x30, 0x1b, 0x64, 0x59, 0x4e, 0x66,
	0x71, 0x89, 0x04, 0x93, 0x02, 0x33, 0xba, 0x65, 0x20, 0x71, 0x90, 0xc1, 0x25, 0xf9, 0x25, 0x89,
	0x39, 0x30, 0x83, 0xc1, 0x9c, 0x24, 0x36, 0xb0, 0xc3, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xbc, 0x35, 0xf4, 0x07, 0xe5, 0x00, 0x00, 0x00,
}
