// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

// protoc -I=. --go_out=. base.proto

package base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Banner struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Link                 string   `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Img                  string   `protobuf:"bytes,3,opt,name=img,proto3" json:"img,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Banner) Reset()         { *m = Banner{} }
func (m *Banner) String() string { return proto.CompactTextString(m) }
func (*Banner) ProtoMessage()    {}
func (*Banner) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *Banner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Banner.Unmarshal(m, b)
}
func (m *Banner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Banner.Marshal(b, m, deterministic)
}
func (m *Banner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Banner.Merge(m, src)
}
func (m *Banner) XXX_Size() int {
	return xxx_messageInfo_Banner.Size(m)
}
func (m *Banner) XXX_DiscardUnknown() {
	xxx_messageInfo_Banner.DiscardUnknown(m)
}

var xxx_messageInfo_Banner proto.InternalMessageInfo

func (m *Banner) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Banner) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Banner) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

type BannerListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BannerListReq) Reset()         { *m = BannerListReq{} }
func (m *BannerListReq) String() string { return proto.CompactTextString(m) }
func (*BannerListReq) ProtoMessage()    {}
func (*BannerListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *BannerListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BannerListReq.Unmarshal(m, b)
}
func (m *BannerListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BannerListReq.Marshal(b, m, deterministic)
}
func (m *BannerListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BannerListReq.Merge(m, src)
}
func (m *BannerListReq) XXX_Size() int {
	return xxx_messageInfo_BannerListReq.Size(m)
}
func (m *BannerListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BannerListReq.DiscardUnknown(m)
}

var xxx_messageInfo_BannerListReq proto.InternalMessageInfo

type BannerListRsp struct {
	Code                 int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	List                 []*Banner `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BannerListRsp) Reset()         { *m = BannerListRsp{} }
func (m *BannerListRsp) String() string { return proto.CompactTextString(m) }
func (*BannerListRsp) ProtoMessage()    {}
func (*BannerListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{2}
}

func (m *BannerListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BannerListRsp.Unmarshal(m, b)
}
func (m *BannerListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BannerListRsp.Marshal(b, m, deterministic)
}
func (m *BannerListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BannerListRsp.Merge(m, src)
}
func (m *BannerListRsp) XXX_Size() int {
	return xxx_messageInfo_BannerListRsp.Size(m)
}
func (m *BannerListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BannerListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BannerListRsp proto.InternalMessageInfo

func (m *BannerListRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BannerListRsp) GetList() []*Banner {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Banner)(nil), "base.Banner")
	proto.RegisterType((*BannerListReq)(nil), "base.BannerListReq")
	proto.RegisterType((*BannerListRsp)(nil), "base.BannerListRsp")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0x2c, 0x4e,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x5c, 0xb8, 0xd8, 0x9c, 0x12,
	0xf3, 0xf2, 0x52, 0x8b, 0x84, 0x44, 0xb8, 0x58, 0x4b, 0x32, 0x4b, 0x72, 0x52, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x21, 0x2e, 0x96, 0x9c, 0xcc, 0xbc, 0x6c, 0x09, 0x26,
	0xb0, 0x20, 0x98, 0x2d, 0x24, 0xc0, 0xc5, 0x9c, 0x99, 0x9b, 0x2e, 0xc1, 0x0c, 0x16, 0x02, 0x31,
	0x95, 0xf8, 0xb9, 0x78, 0x21, 0xa6, 0xf8, 0x64, 0x16, 0x97, 0x04, 0xa5, 0x16, 0x2a, 0xb9, 0xa2,
	0x08, 0x14, 0x17, 0x80, 0xcc, 0x49, 0xce, 0x4f, 0x81, 0x18, 0xce, 0x1a, 0x04, 0x66, 0x0b, 0x29,
	0x80, 0xcc, 0x2e, 0x2e, 0x91, 0x60, 0x52, 0x60, 0xd6, 0xe0, 0x36, 0xe2, 0xd1, 0x03, 0x3b, 0x0e,
	0xa2, 0x2d, 0x08, 0x2c, 0x93, 0xc4, 0x06, 0x76, 0xaa, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x2e,
	0x20, 0xe7, 0xd4, 0xb8, 0x00, 0x00, 0x00,
}
